version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update ownership of npm directory
          command: |
            if [ -d ~/.npm ]; then
              sudo chown -R $(whoami) ~/.npm
            fi
      - run:
          name: Install dependencies
          command: |
            cd MyStore
            npm install
            cd ../mock-API-test
            npm install
      - run:
          name: Install Chrome
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
      - run:
          name: Run tests
          command: |
            cd MyStore
            npx nightwatch
            cd ../mock-api-test
            npm run dev &
            npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
